### ISSUE TITLE
Provide a built-in quit command?

### ISSUE THREAD

**Issue by lu-zero** [arturh85/reedline-repl-rs#16]
Right now, if I did not miss it, there isn't a simple way to `quit` the repl. Would be acceptable to add a default quit and/or provide an example to show how to manage the quit/save pattern?

**Comment by arturh85** [comment]
Well currently there is only a shortcut configured by default which can be disabled using with_stop_on_ctrl_d(false):

> Tip: Search history with CTRL+R, clear input with CTRL+C, exit repl with CTRL+D

If you want to implement a quit command I think you would have to call std::process::exit() with your exit code as I don't see a way for the callback to break out of the main loop in run().

**Comment by lu-zero** [comment]
Implementing it outside the crate requires to do something like this:
https://github.com/sifis-home/sifis-api/commit/92ca9f5467780f6250f45ed8f29a41614de7717e

Might be nice to add a error kind to make the code a little more compact and less hacky.
