### ISSUE TITLE
Support for clap derive?

### ISSUE THREAD

**Issue by jfaust** [arturh85/reedline-repl-rs#23]
I tend to build CLIs with `clap`'s `derive` macros. I've figured out a relatively painless workaround to use these with `reedline-repl-rs`, but was wondering if there's any appetite for first-class support?

Something like:
```rust
#[derive(clap::Parser)]
struct Args { ... }

let mut repl = Repl::new(())
    with_derived::<Args>()
```

**Comment by arturh85** [comment]
I'm not currently working on this project but if someone were to implement this I would happily merge it.
