### ISSUE TITLE
Case insensitive command matching?

### ISSUE THREAD

**Issue by wballoni** [arturh85/reedline-repl-rs#58]
Question: Is there a way to do command matching in a case insensitive way? For example, can I match "exit", "Exit" and "EXIT" with a single `with_command` specification?

I was looking for something like (but open to anything already present or that can be added):
```
Repl::new(()).with_case_insensitive(true) ...
```

**Comment by arturh85** [comment]
we are using clap so I think this could work: https://docs.rs/clap/latest/clap/struct.Arg.html#method.ignore_case
